name: Cloud Function deploy

on: 
  push:
    branches: 
      - master
    paths: 
      - 'functions/**'

jobs:
  build:

    runs-on: [ubuntu-latest]
    
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v1
    - name: Use Node.js 10.x
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - name: Run Yarn
      run: yarn
      working-directory: 'functions'
    - name: Deploy Function to Firebase
      uses: w9jds/firebase-action@master
      with:
        args: deploy --only functions
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
